### ISSUE TITLE
Error on loading

### ISSUE THREAD

**Issue by franjorge** [jotacor/homeassistant-custom_components#1]
Hi,

I am getting this error in the logs:

scanner = AskeyDeviceScanner(config[DOMAIN])
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 42, in __init__
    self.success_init = self._update_info()
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 59, in _update_info
    data = self.get_askey_info()
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 85, in get_askey_info
    for device in devices_data:
UnboundLocalError: local variable 'devices_data' referenced before assignment

**Comment by doctorvanmartin** [comment]
Same problem here:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/setup.py", line 164, in async_device_tracker_scan
    found_devices = await scanner.async_scan_devices()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 46, in scan_devices
    self._update_info()
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 59, in _update_info
    data = self.get_askey_info()
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 85, in get_askey_info
    for device in devices_data:
UnboundLocalError: local variable 'devices_data' referenced before assignment

**Comment by doreks** [comment]
how is going..?


Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/legacy.py", line 231, in async_setup_legacy
    scanner = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 24, in get_scanner
    scanner = AskeyDeviceScanner(config[DOMAIN])
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 42, in __init__
    self.success_init = self._update_info()
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 59, in _update_info
    data = self.get_askey_info()
  File "/config/custom_components/askey_rft3505/device_tracker.py", line 78, in get_askey_info
    response = session.get(url, headers=headers, timeout=4)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)

**Comment by niuzhd** [comment]
humidifier.py
line 64 :
SetHumidity -> targetHumidity
